[project]
name = "custom-install"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "pyaes>=1.6.1",
    "events==0.4",
    "pyctr>=0.4,<0.6",
    "pyside6",
    "comtypes>=1.4.16",
    "pillow>=11.3.0",
    "nuitka[onefile]>=4.0.8",
    "py7zr>=1.0.0",
    "rarfile>=4.2",
    "pyzipper>=0.3.6",
]
