name: CI

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Dependencies
        shell: bash
        run: |
          uv sync
          curl -L -o "./7za.7z" https://github.com/ip7z/7zip/releases/download/26.01/7z2601-extra.7z
          7z x "./7za.7z" -o"7zaout/"
          cp "7zaout/7za.exe" "Tulip3DS/bin/win32/7za.exe"
          cp "7zaout/7za.dll" "Tulip3DS/bin/win32/7za.dll"
          cp "7zaout/7zxa.dll" "Tulip3DS/bin/win32/7zxa.dll"
          curl -L -o "unrarw64.exe" https://www.rarlab.com/rar/unrarw64.exe
          7z x "./unrarw64.exe" -o"unrarout/"
          cp "unrarout/UnRAR.exe" "Tulip3DS/bin/win32/UnRAR.exe"
          curl -L -o "common.7z" https://oasisakari.github.io/web/common.7z
          7z x "./common.7z" -o"Tulip3DS/bin/common" -pTulip3DS
          cd installer
          7z a -tzip "Tulip3DS-installer.zip" *
          cd ..
          cp "installer/Tulip3DS-installer.zip" "Tulip3DS-installer.zip"
          
      - name: Build Executable
        run: |
          uv run ./nuitka-make.bat

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ runner.os }} Build
          path: |
            Tulip3DS.exe
            Tulip3DS-installer.zip
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26-intel]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Dependencies
        shell: bash
        run: |
          uv sync
#          uv add --reinstall "Nuitka[all] @ git+https://github.com/Nuitka/Nuitka.git@factory"
          curl -L -o "./7zz.tar.xz" https://github.com/ip7z/7zip/releases/download/26.01/7z2601-mac.tar.xz
          mkdir "7zzout/"
          tar -xvf "./7zz.tar.xz" -C "7zzout/"
          cp "7zzout/7zz" "Tulip3DS/bin/darwin/7zz"
          chmod +x "Tulip3DS/bin/darwin/7zz"
          curl -L -o "unrar" https://oasisakari.github.io/web/unrar
          cp "unrar" "Tulip3DS/bin/darwin/unrar"
          chmod +x "Tulip3DS/bin/darwin/unrar"
          curl -L -o "common.7z" https://oasisakari.github.io/web/common.7z
          "Tulip3DS/bin/darwin/7zz" x "./common.7z" -o"Tulip3DS/bin/common" -pTulip3DS
          cd installer
          "../Tulip3DS/bin/darwin/7zz" a -tzip "Tulip3DS-installer.zip" *
          cd ..
          cp "installer/Tulip3DS-installer.zip" "Tulip3DS-installer.zip"
          
      - name: Build Executable
        run: |
          uv run ./nuitka-make-macos
          "Tulip3DS/bin/darwin/7zz" a -tzip "Tulip3DS.zip" "Tulip3DS.app"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ runner.os }} Build
          path: |
            Tulip3DS.zip
            Tulip3DS-installer.zip
